### ISSUE TITLE
Please add Korean to the installer.

### ISSUE THREAD

**Issue by VenusGirl** [Ruben2776/PicView#100]
Please add Korean to the installer.

![이미지 001](https://user-images.githubusercontent.com/53147200/234227839-6336cef3-72a2-49e2-b2cd-ae47eb19c5c6.png)

Download the Inno Setup script:
[https://github.com/jrsoftware/issrc/blob/main/Files/Languages/Unofficial/Korean.isl](https://github.com/jrsoftware/issrc/blob/main/Files/Languages/Unofficial/Korean.isl)

Or [INNO Setup - Korean.zip](https://github.com/Ruben2776/PicView/files/11320737/INNO.Setup.-.Korean.zip)

**Comment by Ruben2776** [comment]
Thank you, the installer has been updated for the newest version.

**Comment by VenusGirl** [comment]
Thank you.
