### ISSUE TITLE
Hide taskbar progress

### ISSUE THREAD

**Issue by displayerror** [Ruben2776/PicView#103]
Hi
Is it possible to disable or timeout the taskbar progress bar?
It's quite a handly little feature seeing the file placement relative to the directory - but I'll usually have ~10 random images open at any given time and my taskbar is always flooded with bright green bars :D
![230515_pixview](https://github.com/Ruben2776/PicView/assets/7947310/ebeeced2-dbed-418b-b79a-38757f90bd14)

It's also super distracting as I'm always questioning if a download or installation has stalled.

Would it be possible to somehow disable it or fade it out after say... ~5 seconds of inactivity?

**Comment by Ruben2776** [comment]
I can make an option to disable it in the settings window.
