### ISSUE TITLE
v1.8.5 - Settings portable version are stored in AppData\Local\Ruben2776\PicView_Url_[xxx]\[current version number]

### ISSUE THREAD

**Issue by TheDutchJewel** [Ruben2776/PicView#106]
I use the portable version of PicView, but the settings are stored in `AppData\Local\Ruben2776\PicView_Url_bumtkfjopwgc21z54cosoujltxf5kvsr\[current version number]`.

Ans when I update the program with a new version, the stored settings are ignored and a new subfolder with the current version number is created instead.

Is it possible to save the settings portable?

**Comment by Ruben2776** [comment]
It is possible to change the settings to be portable and I'm looking into implementing it in a future release.

**Comment by Ruben2776** [comment]
@TheDutchJewel 
In version 2.2 and later, settings are now stored in a .json file in the PicView/config directory, making it portable.

**Comment by TheDutchJewel** [comment]
Nice, thank you!
