### ISSUE TITLE
endless loading when opening image on ARM64 version 

### ISSUE THREAD

**Issue by guoweiwei9821** [Ruben2776/PicView#112]
**Describe the bug**
endless loading when opening image on ARM64 version 

**To Reproduce**
1. prepare any image, eg. a png file,
2. open the file with PicView, or drag it into PicView
3. PicView will fail to load the image and showing a endless loading progress indicator

**Expected behavior**
very fast loading picture

**Screenshots**
![Snipaste_2023-06-25_09-52-35](https://github.com/Ruben2776/PicView/assets/44802418/48398a55-e7fb-4b34-872a-9901b3e0dd1a)

** context **
hardware:  Surface Pro X 
os: windows 11

**Comment by Ruben2776** [comment]
Sorry, I don't have any device to test it with. Would you mind telling me if this works for you?
https://sourceforge.net/projects/picview/files/1.8.6/win-arm64.zip/download

**Comment by guoweiwei9821** [comment]
great, it works!


发件人: ***@***.***>
发送时间: 2023年6月27日 17:26
收件人: ***@***.***>
抄送: Kent ***@***.***>; ***@***.***>
主题: Re: [Ruben2776/PicView] endless loading when opening image on ARM64 version (Issue #112)


Sorry, I don't have any device to test it with. Would you mind telling me if this works for you?
https://sourceforge.net/projects/picview/files/1.8.6/win-arm64.zip/download

―
