### ISSUE TITLE
Some languages do not work and other issues

### ISSUE THREAD

**Issue by rellikmil** [Ruben2776/PicView#114]
Hi there, I moved from ImageGlass because the author put some EULA there. I have to admit that PicView is even simpler than ImageGlass. However, I have a few questions.

I select Russian, but French is set. (I don't know why the list of languages is in Russian, although the default is English; but yeah, Windows on Russian)
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/5a8e9a2e-2a52-4bbc-8117-994e39537a98)

If I select Polish, Chinese is enabled (it's not on the list, "китайский" on Russian); if I select French, Korean is enabled; if I select Romanian, Polish is enabled
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/9dfd2029-b82c-429a-9a43-25f6aa161e62)
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/991bc1ea-3542-4341-8a7a-e6e5a91b0c0a)

I also found that the settings window is truncated and you can't scroll down
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/5bdc51d8-1462-4217-807d-6d14b960efd9)

One last question: how do I make the default file associations enabled in Windows?

**Comment by rellikmil** [comment]
If you delete two lines (zh_CN and zh_TW) and reassemble, it will work. But I don't know how to add it in a smart way.
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/aae94364-2ced-4edf-98b7-64707197422a)
Apparently, somehow, Chinese languages didn't make the list.

**Comment by rellikmil** [comment]
> One last question: how do I make the default file associations enabled in Windows?

Yeah, I can make it with "Open file as", but it would take a long time if I put each format (PNG, QOI, etc.) separately like this.

**Comment by Ruben2776** [comment]
The list is in Russian because it gets the translation from your installed version of Windows. I may or may not make a different solution for it.

I'm looking into making a new window where you can select file associations in a future release. 

I've tried to make a new version, where I've added scrollbar to the settings window and I've changed the language selection bias. Can you try and see if it fixes it for you? https://sourceforge.net/projects/picview/files/1.9/issue%20114/

**Comment by rellikmil** [comment]
No, nothing has changed in the languages. The problem is Chinese, because there are two.
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/5629432f-5181-47ff-8f4e-c77811e46dfb)
I think it should be zh-Hans and zh-Hant, exactly with dashes, but dashes are not allowed in enumerations, so therein lies the problem. This probably needs to be rewritten somehow, but now I've built a program for myself, so for now, this is the solution.

As for Settings, cool, but UI settings needs scrolling, and size correction too
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/f9f4da0e-9689-4102-a299-fb1167b04e09)
![изображение](https://github.com/Ruben2776/PicView/assets/24569064/6d6c92ea-d547-424c-a21f-98b83f717ace)

**Comment by Ruben2776** [comment]
I've changed the the language selection logic. Does the latest commit work for you?

**Comment by rellikmil** [comment]
Yep, works fine, many thanks
