### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Aronlele** [Ruben2776/PicView#116]
**Describe the bug**
![image](https://github.com/Ruben2776/PicView/assets/7881859/8771dee1-0c85-4a37-9dba-03a93394a368)

**To Reproduce**
1. right click picture
2. select open way
3. open with PicView always

**Screenshots**
![image](https://github.com/Ruben2776/PicView/assets/7881859/1e6a857a-2c77-49da-89ad-ea4daf809197)

**Additional context**
![image](https://github.com/Ruben2776/PicView/assets/7881859/58ed9a43-4ccc-4655-bb1f-454c6902bb01)

**Comment by Ruben2776** [comment]
Hi there, thanks for your bug report.

Does this version fix it for you?

https://sourceforge.net/projects/picview/files/%23116/PicView.1.9.5%20.NET%207%20required%20win-x64.zip/download

**Comment by Aronlele** [comment]
> Hi there, thanks for your bug report.
> 
> Does this version fix it for you?
> 
> https://sourceforge.net/projects/picview/files/%23116/PicView.1.9.5%20.NET%207%20required%20win-x64.zip/download

ok，This version fix it，thanks
