### ISSUE TITLE
Allow to star and rate images?

### ISSUE THREAD

**Issue by MarcWeber** [Ruben2776/PicView#118]
When viewing images one task often is rating them so that you have an easier time later looking at the good images only.
So it would be nice if keys 1 2 3 4 .. could set 1 to 5 stars or so.

**Comment by nopeless** [comment]
@MarcWeber Is there any other project in mind that does this? Unlike mp3 files, which support has rating system built-in, image files don't really have a standardized way.

**Comment by Ruben2776** [comment]
With version 2.1 and later, the EXIF star rating can be keybinded. It is set to 1,2,3,4 and 5. Pressing 0 will reset it. This can be changed in the About window. The EXIF rating can also be viewed and changed in the Image Info window.
