### ISSUE TITLE
[Bug] Zoom causes crash

### ISSUE THREAD

**Issue by nopeless** [Ruben2776/PicView#121]
Zooming in without image is loaded crashes the application

Null reference error and I believe this is an easy bug to fix. If you are unsure what I am referring to let me know

**Comment by nopeless** [comment]
@me505 If you are interested in this, the project compiles out of the box (fresh clone just compiles straight away). The offending method is here

https://github.com/Ruben2776/PicView/blob/9aea1678a63ef5794f8788ae9ab7d6ab883dd8ac/src/PicView/UILogic/TransformImage/Zoom.cs#L239-L288

Just add a null check

**Comment by BeanieMen** [comment]
What is this.

**Comment by nopeless** [comment]
> What is this.

Its a lightweight .NET WPF image viewer. Kinda like the "Photos" program that comes with a windows install

**Comment by Ruben2776** [comment]
Thanks. It will be fixed in next release.
