### ISSUE TITLE
Exception raises while zooming pictures

### ISSUE THREAD

**Issue by seflerZ** [Ruben2776/PicView#127]
**Describe the bug**
Exception raises while zoom pictures.

**To Reproduce**
Open a JPGE image with latest Windows ARM64 build and zoom in, exception occurs.

**Expected behavior**
Zoomed in.

**Screenshots**
The first line reads:
System.ArgumentException: not a valid BitmapScalingMode value.
![image](https://github.com/Ruben2776/PicView/assets/2093588/af7202aa-adae-4352-967a-5265366e4c58)

**Additional context**
Latest binary win-arm64 build downloaded from Github.

**Comment by Ruben2776** [comment]
Sorry about that. I've made a new build at https://sourceforge.net/projects/picview/files/2.0/PicView%202.0%20.NET%208%20required%20win-arm64.zip/download that should fix it

**Comment by seflerZ** [comment]
It works now! Thank you so much!
