### ISSUE TITLE
Zoom with mousewheel option doesn't work

### ISSUE THREAD

**Issue by DnaVenom88** [Ruben2776/PicView#130]
The option "Zoom with mousewheel" in Settings doesn't work: enabling it and scrolling with the wheel continues to cycle the other images of the folder.
Zoom is only possible with the option "CTRL to zoom" enabled, there's no other option or button to do it

**Comment by Ruben2776** [comment]
Hi there, thank you for notifying me.

I'm sorry for the inconvenience. I'll have it fixed in the next release.

**Comment by Ruben2776** [comment]
Version 2.2 has this fixed.
