### ISSUE TITLE
Auto-rotate based on EXIF orientation

### ISSUE THREAD

**Issue by kristianrl** [Ruben2776/PicView#131]
Can you make PicView auto-rotate images as they are loaded, based on the Exif:Orientation tag?

It currently doesn't work with my photos taken on iPhone 12/13. You can test with files from https://github.com/recurser/exif-orientation-examples

**Comment by Ruben2776** [comment]
Hi there, thanks for reaching out.

I've uploaded a new version for the autorotation.
Can you test if this fixes it for you?

https://sourceforge.net/projects/picview/files/%23131/PicView%202.1%20.NET%208%20required%20win-x64.zip/download

**Comment by kristianrl** [comment]
I tested, and it works - thanks for fixing this!
