### ISSUE TITLE
[bug] Drop&down crash

### ISSUE THREAD

**Issue by emako** [Ruben2776/PicView#135]
**Describe the bug**

**To Reproduce**
1. Drop&down an .mp3 file
2. Drop&down an .mp3 file again

**Expected behavior**
See Screenshots

**Screenshots**
![image](https://github.com/Ruben2776/PicView/assets/24737061/e470bb7b-4a1f-4916-9d91-edfcf8ca12a6)

**Additional context**

**Comment by Ruben2776** [comment]
Thank you for reporting. I'll have the bug fixed in the next release.

However, I'm afraid I'm not planning to support viewing cover art from .mp3 files.

**Comment by emako** [comment]
OK
