### ISSUE TITLE
Crash when opening hidden files

### ISSUE THREAD

**Issue by TomberWolf** [Ruben2776/PicView#140]
**Describe the bug**
I got crashes when I want to open hidden files.

**To Reproduce**
1. Make a file hidden
2. Double click it
3. See error

**Expected behavior**
Should open and view the hidden file.
![explorer_20240311163403621](https://github.com/Ruben2776/PicView/assets/9993839/07774e5c-fcd0-4647-a16c-d140fda753e5)

**Screenshots**

**Additional context**

**Comment by Ruben2776** [comment]
Thank you for your bug report.

It will be fixed in the next release.

**Comment by Ruben2776** [comment]
The changes has been added in the 2.2.4 release.
