### ISSUE TITLE
Default instalation path is the C:\ ????

### ISSUE THREAD

**Issue by larinius** [Ruben2776/PicView#142]
Executed command: "winget install picview"
Got picview installed directly into the C:\ folder.

Do you ever heard about default installation path like "Program files" or User ? At least ask user to confirm path. 
Such installation in 2024 looks like a prank...

**Comment by Ruben2776** [comment]
Downloading the .exe installer will allow you to install the program at your preferred location. 
You can also download the zip archives and extract it where you wish.

The reason for the default directory is due to challenges with having read access on Windows.
