### ISSUE TITLE
PicView seems having trouble to find the central point

### ISSUE THREAD

**Issue by MononeV** [Ruben2776/PicView#143]
**Describe the bug**
Hi, there. I just got to know this project few days ago, and I'm having some issues with the window position. After some tests, I'm thinking it might be something related to the center detection.

**To Reproduce**
There are couple of situations:
1. When 'auto fit window' set to on, the window position is random when changing between pictures.

https://github.com/Ruben2776/PicView/assets/39477101/ceb0b7ad-3357-456b-b96f-273e372df247

2. When 'auto fit window' set to off, the window position is fixed, but press space would make it off-screen.

https://github.com/Ruben2776/PicView/assets/39477101/27ea77da-68ae-4e0b-81b6-e3ea6a3afba7

3. Press F11 at anytime would make the window maximum, but also off-screen.

https://github.com/Ruben2776/PicView/assets/39477101/fd36448f-a281-4551-b1e0-f93c5c82f558

**Expected behavior**
I'm running Windows 11 at 1080p with 100% scale so there should be no problem with my setup.

**Comment by Heart1010** [comment]
Has this anything todo with my "small problem"? PicView always starts at this postition on my win10 pc - why?! The bottom part is always out of the view 🤔 

**And yes, it's still the same with newest v2.2.4**

![2024-03-28_Screenshot_3752](https://github.com/Ruben2776/PicView/assets/1481680/2f22d700-52a3-4a6a-af0a-2c0e7bd172e7)

**Comment by Ruben2776** [comment]
@MononeV 
I've made the changes to version 2.2.4

**Comment by Ruben2776** [comment]
@Heart1010 
I'll take a look at your issue

**Comment by MononeV** [comment]
> @MononeV I've made the changes to version 2.2.4

I can confirm that the issues have been fixed. Many thanks, feel free to close the issue.
