### ISSUE TITLE
ARM64 builds fail to start

### ISSUE THREAD

**Issue by ArminiusTux** [Ruben2776/PicView#144]
**Describe the bug**
PicView.exe (ARM64 build) fails to start properly, despite having the latest .NET runtime v8.0.3

**To Reproduce**
Download any of the portable WinARM64 builds from v2.2.4 down to v2.2.1

**Expected behavior**
Instant startup without errors, just as in v2.2

**Screenshots**
![grafik](https://github.com/Ruben2776/PicView/assets/44533868/b5b1e559-76fe-45a9-9196-c65d86831544)

**Additional context**
Although several subfolders are missing from the WinARM64 packages, copying the sole folder "Config" over from e.g. v2.2 into the portable main folder of any later version fixes the error.

**Comment by Ruben2776** [comment]
Hi there, thanks for reporting the issue.

I'm sorry for the inconvenience.
There was an error in my build script for the arm64 versions. I have re-uploaded the arm 64 with the missing files and directories.

**Comment by ArminiusTux** [comment]
Dear @Ruben2776,

thanks for the lightning-fast response and indeed for the quick fix, now is everything running as it should.

If you need an easy-to-setup virtualisation environment for WinARM64, give [dockur](https://github.com/dockur/windows-arm) a try.😉

Happy Easter!

**Comment by Ruben2776** [comment]
Thanks for the kind words. I'll give the dockur a try. 

Happy Easter as well.
