### ISSUE TITLE
Image effects window some item text not shown (no text label)

### ISSUE THREAD

**Issue by netcharm** [Ruben2776/PicView#146]
Image effects window some item text not shown (no text label)
![图片](https://github.com/Ruben2776/PicView/assets/1257071/03165c2e-536a-42df-92d2-2f35fe8537a4)

**Comment by Ruben2776** [comment]
Thank you for the bug report.

I'll have it fixed in the next release

**Comment by Ruben2776** [comment]
The changes has been added in the 2.2.5 version.
