### ISSUE TITLE
PicView always starts at this postition on my win10 pc - why?! The bottom part is always out of the view 🤔

### ISSUE THREAD

**Issue by Ruben2776** [Ruben2776/PicView#149]
Has this anything todo with my "small problem"? PicView always starts at this postition on my win10 pc - why?! The bottom part is always out of the view 🤔 

**And yes, it's still the same with newest v2.2.4**

![2024-03-28_Screenshot_3752](https://github.com/Ruben2776/PicView/assets/1481680/2f22d700-52a3-4a6a-af0a-2c0e7bd172e7)

_Originally posted by @Heart1010 in https://github.com/Ruben2776/PicView/issues/143#issuecomment-2025029199_

**Comment by Ruben2776** [comment]
I've tried to replicate your issue, though I'm unable to reproduce it. Is it possible you can provide me further details? 
@Heart1010

**Comment by Heart1010** [comment]
How can I help you further here? What infos do you need?

**Comment by Ruben2776** [comment]
If you click the space bar button, will it center the window? 
Do you have scaling enabled in Windows? I.E, if you go to Display Settings does the setting scale and layout have a different value than 100%?

Have you tried resetting the settings for PicView? You can reapply them afterwards. 
To reset the settings, navigate to the directory PicView is in and delete the `UserSettings.json` file inside the `Config` folder. 
If that didn't change anything, PicView may not have writing permissions required to save the settings, and there should be another config in the roaming directory, at `%AppData%\Ruben2776\PicView\Config\UserSettings.json`. 
Try to see if that file exists and delete both of them and then reapply your settings.

I'll have a new option in the settings window in the next release to reset settings to default.

**Comment by Heart1010** [comment]
> If you click the space bar button, will it center the window?

I open PicView - it is not centered (like described in my issue) and then press `space` on my keyboard then PicView is centered correct, yes 👍 

> Do you have scaling enabled in Windows? I.E, if you go to Display Settings does the setting scale and layout have a different value than 100%?

No, I use two monitors - both are set to 100%
![image](https://github.com/Ruben2776/PicView/assets/1481680/c1546df8-80fb-48fa-b66b-51f2a64f2226)

I deleted `UserSettings.json` in the PicView Config directory and after that PicView started correct at the center!!!
But when I now make some changes in the settings and exit PicView this UserSettings.json file is not generated at all (also not in the roaming directory) - so my setting changes are not stored at all.

**Comment by Ruben2776** [comment]
Sorry about the inconvenience. 

The issue is cause of Windows not giving writing permissions to save settings. 

To solve the issue, you can run PicView as admin (when you need to save settings) or reinstall it to a new location, with writing permission (usually somewhere else than E.G, C:\Program Files)

Additionally, I've uploaded a new version to fix the saving issue. I would appreciate it if you would download a new version here https://sourceforge.net/projects/picview/files/%23149%2C%23137/, extract it and replace the files where PicView is located on your machine and tell me if it fixes your issue, instead of running it as admin or reinstalling it.

**Comment by Heart1010** [comment]
The new version stores my changed settings 👍 

When I see it correct you now save UserSettings.json file in roaming directory in such cases?
`C:\Users\myuser\AppData\Roaming\Ruben2776\PicView\Config\UserSettings.json`

**Comment by Ruben2776** [comment]
Thank you for confirming.

Yes, it's supposed to save and read from there in case of lack of writing permissions.

**Comment by Ruben2776** [comment]
The changes has been added in the 2.2.5 version.
