### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by Charltsing** [Ruben2776/PicView#152]
![1](https://github.com/Ruben2776/PicView/assets/19963715/a6adcdc4-0c2f-48bb-9760-dcd7e1493075)

System.InvalidOperationException
  HResult=0x80131509
  Message=调用线程必须为 STA，因为许多 UI 组件都需要。
  Source=PresentationCore
  StackTrace:
   在 System.Windows.Input.InputManager..ctor()
   在 System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   在 System.Windows.Input.KeyboardNavigation..ctor()
   在 System.Windows.FrameworkElement.FrameworkServices..ctor()
   在 System.Windows.FrameworkElement..ctor()
   在 System.Windows.Controls.Control..ctor()
   在 PicView.WPF.Views.UserControls.Misc.DragDropOverlay..ctor() 在 C:\Users\liucq\Desktop\PicView-dev\PicView-dev\src\PicView.WPF\Views\UserControls\Misc\DragDropOverlay.xaml.cs 中: 第 8 行
   在 PicView.WPF.UILogic.DragAndDrop.ImageDragAndDrop.AddDragOverlay() 在 C:\Users\liucq\Desktop\PicView-dev\PicView-dev\src\PicView.WPF\UILogic\DragAndDrop\Image_DragAndDrop.cs 中: 第 234 行
   在 PicView.WPF.UILogic.DragAndDrop.ImageDragAndDrop.<Image_DragEnter>d__1.MoveNext() 在 C:\Users\liucq\Desktop\PicView-dev\PicView-dev\src\PicView.WPF\UILogic\DragAndDrop\Image_DragAndDrop.cs 中: 第 91 行
   在 PicView.WPF.Views.Windows.MainWindow.<>c.<<-ctor>b__0_14>d.MoveNext() 在 C:\Users\liucq\Desktop\PicView-dev\PicView-dev\src\PicView.WPF\Views\Windows\MainWindow.xaml.cs 中: 第 126 行

![捕获](https://github.com/Ruben2776/PicView/assets/19963715/24af3599-d6a2-43c8-8b8c-1e73f843dde7)

**Comment by Ruben2776** [comment]
Thanks for your bug report.

This has been added in the 2.2.6 release.
