### ISSUE TITLE
2.3.0 NET8-required Package language files are missing

### ISSUE THREAD

**Issue by BlackRosePetals** [Ruben2776/PicView#155]
![7zFM_bJTyo6P758](https://github.com/Ruben2776/PicView/assets/53809038/1975352d-35f5-4838-a9ce-10f209b32a25)

Other than the traditional Chinese language version, all the other language files are not packaged.

**Comment by Ruben2776** [comment]
Hey there,

I just downloaded every version to check, but none of the language files are missing. 
If you are missing some language files, you can redownload a version. 

You don't need additional languages, so if you only want to use the traditional Chinese language, you are welcome to delete the other files (or not redownload them).

**Comment by BlackRosePetals** [comment]
Please check PicView-v.2.3.0-win-x64-.NET8-required.7z and PicView-v.2.3.0-win-x64-.NET8-required.zip,I re-downloaded it, the ZIP package is still only zh-TW language files.

Sorry, I forgot to specify the specific documents just now.

**Comment by Ruben2776** [comment]
I cannot reproduce your error. 

You can find the files here:
https://github.com/Ruben2776/PicView/tree/dev/src/PicView.Core/Config/Languages

or you can try download these:
https://www.fosshub.com/PicView.html?dwl=PicView-v.2.3.0-win-x64-.NET8-required.7z
https://www.fosshub.com/PicView.html?dwl=PicView-v.2.3.0-win-x64-.NET8-required.zip

or from SourceForge:
https://sourceforge.net/projects/picview/files/2.3/
