### ISSUE TITLE
Window wrongly positionned on High-DPI screen

### ISSUE THREAD

**Issue by SpringsTS** [Ruben2776/PicView#16]
**Describe the bug**
When launching PicView on my high-DPI screen (4K resolution on 17" screen, with zoom set as 200% in Windows), the window is not centered in the screen but partially outside the visible area in the bottom-right corner.
The problem does not appear if I launch PicView without image, and the window size is correctly set.

**To Reproduce**
1. In the Windows 10 Settings app, Display section, set a zoom factor to 200%
2. Apply the settings
3. Open any picture with PicView

Thank you in advance for the resolution.

**Comment by Ruben2776** [comment]
Hi there! Thanks for reaching out.

I'll make a new release soon with it fixed.

**Comment by Ruben2776** [comment]
Hi there @SpringsTS, sorry for the slow response.

Are you still having issues in 0.9.9.5? I will try and optimize it more for low resolutions and High-DPI cases in the future.

**Comment by SpringsTS** [comment]
Hello,

I could give a quick try today, and it works perfectly, thank you!

I will have another point for you but not related to DPI settings.

Keep up the good work 👍
