### ISSUE TITLE
[2.3.2] System.IO.FileNotFoundExcetion errors

### ISSUE THREAD

**Issue by Heart1010** [Ruben2776/PicView#160]
Getting these errors when I try to start PicView v2.3.2 (Win10) - installed the new version as usual with the PicView-2.3.2.exe file.

![image](https://github.com/user-attachments/assets/11093f17-69b6-4509-8b7e-4eab4222d225)

**Comment by Ruben2776** [comment]
I'm sorry for the inconvenience. I had attempted to clean up the builds to reduce file size. I have made a new release again, with updated packages that redirects from using Windows Forms.

**Comment by Heart1010** [comment]
working with the newly uploaded version again - thanks 👍
