### ISSUE TITLE
Avalonia - Don't leave picture borders while zooming in, and limit zooming out like WPF version

### ISSUE THREAD

**Issue by JFMugen** [Ruben2776/PicView#168]
**Is your feature request related to a problem? Please describe.**
WPF version had an option to limit 'zoom out' but you could 'zoom in' to right side of an image and totally skip past it. Here an example. 

https://github.com/user-attachments/assets/9834f222-1dce-49d5-bffe-b3ce181cbfe4

**Describe the solution you'd like**
I would like to see both 'limit zoom out' and 'limit zoom in' options to keep the image inside the window and visible all the time.

**Comment by Ruben2776** [comment]
Thanks for pointing out the missing zoom functionalities. 
I have pushed new versions out to adjust zooming and fix issues.
