### ISSUE TITLE
Program doesn't start

### ISSUE THREAD

**Issue by Alex-V69** [Ruben2776/PicView#169]
**Describe the bug**
The program doesn't start and crashes with an error.

**To Reproduce**
 1. Download PicView-v.2.3.2-win-x64-.NET9-required.zip
 2. Unpack it to system drive.
 3. Try to start PicView.exe one time without .NET9.
 4. Install .NET9.
 5. Try to start it again.
 
**Expected behavior**
No error.

**Screenshots**

<img width="572" alt="error" src="https://github.com/user-attachments/assets/84f5d695-8e5c-419e-9456-6148c45da543">

**Comment by Ruben2776** [comment]
Sorry for the inconvenience. This has been fixed with the 2.3.3 release version.

**Comment by JohnnyBravo75** [comment]
2.3.3 does not start by me

Name der fehlerhaften Anwendung: PicView.exe, Version: 2.3.3.0, Zeitstempel: 0x67200000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.964, Zeitstempel: 0x812662a7
Ausnahmecode: 0xc0000602
Fehleroffset: 0x000000000010b39c
ID des fehlerhaften Prozesses: 0x5828
Startzeit der fehlerhaften Anwendung: 0x01db3ec308200b82
Pfad der fehlerhaften Anwendung: C:\Program Files\PicView\PicView.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 101a71d2-32a8-4b17-ac0e-5cd5da0c9089
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
