### ISSUE TITLE
I want a setting that allows me to set the zoom speed with mouse scroll wheel

### ISSUE THREAD

**Issue by HoustonNguyen** [Ruben2776/PicView#20]
It would be nice to have a way to control how fast zoom happens with the mouse scroll wheel. Currently, it feels rather slow and takes a long time to zoom in really close.

In the settings dialog, I would like a section that allows me to control the zoom; this could take the form of some sort of slider, but open to suggestions.

**Comment by Ruben2776** [comment]
Thanks for your suggestion. 

I'm planning to make a new release by Monday and would be able to have that implemented.

**Comment by Ruben2776** [comment]
With the recent release 0.9.9.7 the zoom speed has been changed. 
However, It can't be changed in the settings window as of yet. I am planning to redesign the settings window in a future release and have the option of allowing the user to change the zoom speed by then.

**Comment by Ruben2776** [comment]
Hello @HoustonNguyen with the latest release of PicView 0.9.9.8 the zoom speed can be changed in the new redesigned settings window. 

I hope you are having a great day!
