### ISSUE TITLE
x64 installed to C:\Program Files (x86)\PicView

### ISSUE THREAD

**Issue by ivysrono** [Ruben2776/PicView#23]
PicView 1.0.0
Win10 x64
Why not C:\Program Files\PicView

**Comment by Ruben2776** [comment]
Sorry for the inconvenience. Having installed it in the x86 folder will not cause any issues. You may choose to install it wherever you like.
I've had some challenges with finding an installer that worked for me and was free and I'm looking into a better solution in the future.
