### ISSUE TITLE
Unable to rotate Images

### ISSUE THREAD

**Issue by Alien-Guy** [Ruben2776/PicView#25]
There is no option to rotate an image. If an image is loaded upside down there is no option to rotate it to the proper orientation.

Please fix this issue!

**Comment by Ruben2776** [comment]
You can use the arrow Up and Down keys to rotate it.

**Comment by Alien-Guy** [comment]
Thanks for info. I was able to rotate images by using **PgUP** and **PgDn** buttons. But I thing a **GUI** radio button in PicView will be a better option. Will you consider adding such a button in PicView GUI in future.

More I am having one more Issue: I am unable to set PicView as my **default pic viewer** as in the dropdown of programmes  to be set as default picture viewers, PicViw simply doesn't show up. I am using Wiindows 10 64-bit latest build.

**Comment by Ruben2776** [comment]
![Screenshot 2020-11-04 173931](https://user-images.githubusercontent.com/4200419/98139722-cc9a0000-1ec4-11eb-993f-37ddb224a2db.png)
You can use the two highlighted buttons in the screenshot to rotate the image left or right

![Screenshot 2020-11-04 174523](https://user-images.githubusercontent.com/4200419/98140480-c8221700-1ec5-11eb-9100-da4512016ec1.png)
For setting it as default image viewer, you can go to the settings window by clicking `F4`  or clicking on the hammer icon, as shown in the screenshot and then clicking the colored `Set as default image viewer`, then choose which formats you want it to open with and click `Apply`.

**Comment by Alien-Guy** [comment]
Thanks.
