### ISSUE TITLE
Support for animated GIFs

### ISSUE THREAD

**Issue by Mennaruuk** [Ruben2776/PicView#29]
**Is your feature request related to a problem? Please describe.**
PicView supports a wide assortment of image filetypes. While GIF is one of them, animated GIFs are not.

**Describe the solution you'd like**
I would like to know if PicView can support playing animated GIFs, as this is vital for me not to have another program installed just to play one image filetype.

**Describe alternatives you've considered**
I tried opening the GIF right from within PicView as opposed to opening the image directly. Didn't help. The animation still played in Internet Explorer, Firefox, IrfanView, Windows Photo Viewer, Photos, etc.

**Additional context**
Running latest version of PicView on latest release of Windows 10.

**Example animated GIF**
![](https://upload.wikimedia.org/wikipedia/commons/3/34/Parallax_scrolling_example_scene.gif)

**Comment by Ruben2776** [comment]
Hi there, thanks for your feature request.

I'm looking into different solutions on how to implement support for playing animated gifs and would like to add it in a future release.

**Comment by Mennaruuk** [comment]
Appreciate it! Love your tool

**Comment by Ruben2776** [comment]
Sorry for the late work, I haven't been well, but I am better now and back to working on it. version 1.3 https://github.com/Ruben2776/PicView/releases/tag/1.3 has been uploaded with animated .GIF support.

**Comment by Mennaruuk** [comment]
THANK YOU SO FREAKIN’ MUCH! Don’t worry about it, I really appreciate your considering it in the first place. Now I can finally open animated GIFs with PicView and stop using the bloat that is Windows Photos.
