### ISSUE TITLE
Opening settings in fullscreen mode should get focus

### ISSUE THREAD

**Issue by mirh** [Ruben2776/PicView#30]
**To Reproduce**
1. Open some image in fullscreen
2. Right click > settings > show all settings window
3. The thing stays in the background

**Expected behavior**
Either the window gets in the foreground while maintaining fullscreen, or fullscreen is disabled with focus on such window. 

**Additional context**
Idk if setting windows should be supposed to always be in the foreground while opened, or just be treated as a normal window.

**Comment by Ruben2776** [comment]
This issue has been fixed in version 1.3.5 https://github.com/Ruben2776/PicView/releases/tag/1.3.5 
Sorry for the long update time.
