### ISSUE TITLE
Add PicView to package managers

### ISSUE THREAD

**Issue by Ruben2776** [Ruben2776/PicView#43]
Planning to add PicView to:
* Chocolatey
* Winget
* Scoop

**Comment by tesar-tech** [comment]
Yes please!

**Comment by Ruben2776** [comment]
I've created a new directory called `scripts` to contain setup scripts to make it work for package managers. 
However it's a real headache reading through tons of documentation, trying to make something work I've had no prior experience with. 
So it would be appreciated if anyone would be willing to lend a hand. Pull requests are accepted.

**Comment by Ruben2776** [comment]
Alright, Chocolatey should probably work now with
`choco install picview --version=1.5.6 -y`

Now gotta figure out how to make portable version work.

**Comment by tesar-tech** [comment]
Thank you. Now picview is my default image app.

**Comment by aliesbelik** [comment]
Merged into `Extras` bucket: ScoopInstaller/Extras#13389.
