### ISSUE TITLE
Fullscreen - Image Info Crash

### ISSUE THREAD

**Issue by Yevrag35** [Ruben2776/PicView#48]
**Describe the bug**
When in fullscreen, attempting to show the 'Image Info' window crashes the app.

**To Reproduce**
1. Open any image.
2. Go into Fullscreen mode.
3. Right-click the image, and select "Image Info".

**Expected behavior**
The "Image Info" window (box) should present itself the same way the button works when not in fullscreen mode.

**Additional context**
The issue looks to be a null reference exception from UILogic\ConfigureWindow.cs -- https://github.com/Ruben2776/PicView/blob/f0cdcfdf03db191c24c522d02e6b4ca51c3562a2/PicView/UILogic/ConfigureWindows.cs#L158

It can be fixed by changing the line to
```csharp
GetImageInfoWindow.Topmost = true;
```

**Comment by Ruben2776** [comment]
Hi there,

Thanks for bringing this issue to my attention and providing a fix for it. The issue has been fixed in the 1.5.1 release.
Have a great day!
