### ISSUE TITLE
trying to write stars on files with `archive` attribute will corrupt files

### ISSUE THREAD

**Issue by cannibalox** [Ruben2776/PicView#52]
**Describe the bug**
tried to write ratings/stars on a file with attribute `archive`
![image](https://user-images.githubusercontent.com/4605693/140317598-1d736d00-9116-4215-8e36-89897cb4dbda.png)

-> app crashed and the image is now 0 bytes.

expected behavior: file should be unmodified

using v1.5.6 test (the one with the zoom out feature) on win10 x64

**Comment by Ruben2776** [comment]
I tried saving EXIF rating on a .jpg with these two ticked 
![image](https://user-images.githubusercontent.com/4200419/140336445-2b995ce4-bd02-4c7d-a0c3-253b80fd461f.png)
and it worked as expectedd

Writing EXIF data is done with [Magick.NET](https://github.com/dlemstra/Magick.NET) so if your particular case isn't working, you might have to create an issue there. I can't really replicate your issue.

**Comment by cannibalox** [comment]
thank you for looking into it. it seemed it was related to using a network share, I'm unable to repro using a local drive.
