### ISSUE TITLE
InnoSetup installation wizard Chinese language interface garbled

### ISSUE THREAD

**Issue by wcxu21** [Ruben2776/PicView#57]
InnoSetup installation wizard Chinese language interface garbled。

If you run the installation wizard in a simplified Chinese system, there will be garbled Chinese characters in the installation interface, which will cause it to be incorrect.

Please check the InnoSetup Simplified Chinese language file, its file encoding should be UTF-8-BOM encoding（.lng） or GB2312（.isl）.

Thank you for your work! ：-）

**Comment by Ruben2776** [comment]
Thanks for bringing this to my attention. I'll try and correct it for next release.

**Comment by Ruben2776** [comment]
PicView 1.6.1 installer has been released with an `UTF-8-BOM` encoding for the `ChineseSimplified.isl` based on https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation

**Comment by wcxu21** [comment]
Nice！
Thanks for your work, it works fine after I tested it.
：-D
