### ISSUE TITLE
Easily accessible button to switch between scroll wheel functionality?

### ISSUE THREAD

**Issue by TomArrow** [Ruben2776/PicView#98]
**Is your feature request related to a problem? Please describe.**
I like to navigate without using my keyboard. The scrollwheel image switching is really comfortable, but if I have to press Ctrl+ for it, then it's no longer good for me. But I want the main function of the scrollwheel to be zooming.

**Describe the solution you'd like**
Some small button to switch this functionality instead of having to go to Settings? That would make it super comfortable to do everything. 

**Describe alternatives you've considered**
Or maybe it could be a button that you click and hold mouse button pressed and then that allows you to do switching of images. But then it would suddenly stop making sense if the setting is reversed because you couldn't reasonably zoom with that.

**Additional context**
None

**Comment by Ruben2776** [comment]
I can make it an option for the context menu (right click menu) and add a keyboard shortcut for it.

**Comment by TomArrow** [comment]
Hmm that would be a bit better but still need an extra click. I often just operate my PC only using a mouse without keys. Would be epic to just need 1 extra click.
